# compose.override.yaml
services:
  api:
    build:
      target: dev # Surcharge : utilise l'étape DEV du Dockerfile
    volumes:
      - ./:/var/www/html # Branche le code de votre ordinateur en direct
      - api_var_cache:/var/www/html/var/cache
    environment:
      - APP_ENV=dev
    extra_hosts:
      - "VM-TEST:172.16.25.3"

  nginx:
    ports:
      - "8000:80" # En dev, on accède via localhost:8080
    volumes:
      - ./:/var/www/html:ro

  mercure:
    environment:
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:3001
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile

volumes:
    api_var_cache:
